# Generated by Django 6.0 on 2026-01-04 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TontineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_group_link', models.URLField(blank=True, max_length=500, null=True)),
                ('caisse_totale', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('en_attente_de_deblocage', models.BooleanField(default=False)),
                ('nombre_approbations', models.IntegerField(default=0)),
                ('admin_groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to=settings.AUTH_USER_MODEL)),
                ('dernier_gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gains', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('a_approuve_session', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='tontine.tontinegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_api', models.CharField(max_length=100, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.membership')),
            ],
        ),
    ]
