# Generated by Django 6.0 on 2026-01-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tontine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueGagnant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_gagne', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_choix', models.DateTimeField(auto_now_add=True)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontinegroup')),
            ],
        ),
    ]
